name: "macOS"

on:
  push:
    branches: ["master"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["master"]

jobs:
  make:
    name: Build Swirc on macOS
    runs-on: macos-latest

    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - run: |
        brew install hunspell
        brew install libressl
        ./configure --without-libintl
        make
